export const menuData = [
  "Naslovna",
  "Danas",
  {
    title: "Politika",
    children: ["Bezbednost"],
  },
  "Svet",
  "Crna hronika",
  "Ekonomija",
  {
    title: "Društvo",
    children: [
      "Događaji",
      "Kultura",
      "Obrazovanje",
      "Tehnologija",
      "Turizam",
      "Zdravlje i život",
    ],
  },
  "Sport",
  {
    title: "Lokal",
    children: [
      {
        title: "Gradovi",
        children: [
          "Beograd",
          "Novi Sad",
          "Niš",
          "Bor",
          "Bajina Bašta",
          "Čačak",
          "Jagodina",
          "Kikinda",
          "Kosovska Mitrovica",
          "Kragujevac",
          "Kraljevo",
          "Kruševac",
          "Leskovac",
          "Loznica",
          "Novi Pazar",
          "Požarevac",
          "Pančevo",
          "Priština",
          "Pirot",
          "Prokuplje",
          "S. Mitrovica",
          "Smederevo",
          "Sombor",
          "Subotica",
          "Šabac",
          "Užice",
          "Valjevo",
          "Vranje",
          "Vršac",
          "Zaječar",
          "Zrenjanin",
        ],
      },
      {
        title: "Okruzi",
        children: [
          "Borski okrug",
          "Braničevski okrug",
          "Jablanički okrug",
          "Južnobački okrug",
          "Južnobanatski okrug",
          "Kolubarski okrug",
          "Kosovo i Metohija",
          "Mačvanski okrug",
          "Moravički okrug",
          "Nišavski okrug",
          "Pčinjski okrug",
          "Pirotski okrug",
          "Podunavski okrug",
          "Pomoravski okrug",
          "Rasinski okrug",
          "Raški okrug",
          "Severnobački okrug",
          "Severnobanatski okrug",
          "Srednjobanatski okrug",
          "Sremski okrug",
          "Šumadijski okrug",
          "Toplički okrug",
          "Zaječarski okrug",
          "Zapadnobački okrug",
          "Zlatiborski okrug",
        ],
      },
    ],
  },
  "Region",
];
