export const nameToSlugMap: Record<string, string> = {
    Naslovna: '', // display all posts
    Politika: 'politika',
    Energetika: 'energetika',
    Privreda: 'privreda',
    Bezbednost: 'bezbednost',
    Ekonomija: 'ekonomija',
    Društvo: 'drustvo',
    Obrazovanje: 'obrazovanje',
    Tehnologija: 'tehnologija',
    Turizam: 'turizam',
    Zdravstvo: 'zdravstvo',
    Sport: 'sport',
    Kultura: 'kultura',
    Događaji: 'dogadjaji',
    Region: 'region',
    Planeta: 'planeta',
    'Latin | Ćirilica': 'latin-cirilica',
    Lokal: 'lokal',
    Beograd: 'beograd',
    Gradovi: 'gradovi',
    Okruzi: 'okruzi',
    Barajevo: 'barajevo',
    Čukarica: 'cukarica',
    Grocka: 'grocka',
    Lazarevac: 'lazarevac',
    Mladenovac: 'mladenovac',
    'Novi Beograd': 'novi-beograd',
    Palilula: 'palilula',
    Obrenovac: 'obrenovac',
    Rakovica: 'rakovica',
    'Savski venac': 'savski-venac',
    Sopot: 'sopot',
    'Stari grad': 'stari-grad',
    Surčin: 'surcin',
    Voždovac: 'vozdovac',
    Vračar: 'vracar',
    Zemun: 'zemun',
    Zvezdara: 'zvezdara',
    'Borski okrug': 'borski-okrug',
    'Braničevski okrug': 'braničevski-okrug',
    'Jablanički okrug': 'jablanički-okrug',
    'Južnobački okrug': 'južnobački-okrug',
    'Južnobanatski okrug': 'južnobanatski-okrug',
    'Kolubarski okrug': 'kolubarski-okrug',
    'Kosovo i Metohija': 'kosovo-i-metohija',
    'Mačvanski okrug': 'mačvanski-okrug',
    'Moravički okrug': 'moravički-okrug',
    'Nišavski okrug': 'nišavski-okrug',
    'Pčinjski okrug': 'pčinjski-okrug',
    'Pirotski okrug': 'pirotski-okrug',
    'Podunavski okrug': 'podunavski-okrug',
    'Pomoravski okrug': 'pomoravski-okrug',
    'Rasinski okrug': 'rasinski-okrug',
    'Raški okrug': 'raški-okrug',
    'Severnobački okrug': 'severnobački-okrug',
    'Severnobanatski okrug': 'severnobanatski-okrug',
    'Srednjobanatski okrug': 'srednjobanatski-okrug',
    'Sremski okrug': 'sremski-okrug',
    'Šumadijski okrug': 'šumadijski-okrug',
    'Toplički okrug': 'toplički-okrug',
    'Zaječarski okrug': 'zaječarski-okrug',
    'Zapadnobački okrug': 'zapadnobački-okrug',
    'Zlatiborkski okrug': 'zlatiborkski-okrug'
};