export const nameToSlugMap: Record<string, string> = {
    Naslovna: '',
    Politika: 'politika',
    Energetika: 'energetika',
    Privreda: 'privreda',
    Bezbednost: 'bezbednost',
    Ekonomija: 'ekonomija',
    Društvo: 'drustvo',
    Obrazovanje: 'obrazovanje',
    Tehnologija: 'tehnologija',
    Turizam: 'turizam',
    Zdravstvo: 'zdravstvo',
    Sport: 'sport',
    Kultura: 'kultura',
    Događaji: 'dogadjaji',
    Lokal: 'lokal',
    Region: 'region',
    Planeta: 'planeta',

    Beograd: 'beograd',
    Gradovi: 'gradovi',
    Okruzi: 'okruzi',

    Barajevo: 'barajevo',
    Čukarica: 'cukarica',
    Grocka: 'grocka',
    Lazarevac: 'lazarevac',
    Mladenovac: 'mladenovac',
    'Novi Beograd': 'novi-beograd',
    Palilula: 'palilula',
    Obrenovac: 'obrenovac',
    Rakovica: 'rakovica',
    'Savski venac': 'savski-venac',
    Sopot: 'sopot',
    'Stari grad': 'stari-grad',
    Surčin: 'surcin',
    Voždovac: 'vozdovac',
    Vračar: 'vracar',
    Zemun: 'zemun',
    Zvezdara: 'zvezdara',

    'Borski okrug': 'borski-okrug',
    'Braničevski okrug': 'branicevski-okrug',
    'Jablanički okrug': 'jablanicki-okrug',
    'Južnobački okrug': 'juznobacki-okrug',
    'Južnobanatski okrug': 'juznobanatski-okrug',
    'Kolubarski okrug': 'kolubarski-okrug',
    'Kosovo i Metohija': 'kosovo-i-metohija',
    'Mačvanski okrug': 'macvanski-okrug',
    'Moravički okrug': 'moravicki-okrug',
    'Nišavski okrug': 'nisavski-okrug',
    'Pčinjski okrug': 'pcinjski-okrug',
    'Pirotski okrug': 'pirotski-okrug',
    'Podunavski okrug': 'podunavski-okrug',
    'Pomoravski okrug': 'pomoravski-okrug',
    'Rasinski okrug': 'rasinski-okrug',
    'Raški okrug': 'raski-okrug',
    'Severnobački okrug': 'severnobacki-okrug',
    'Severnobanatski okrug': 'severnobanatski-okrug',
    'Srednjobanatski okrug': 'srednjobanatski-okrug',
    'Sremski okrug': 'sremski-okrug',
    'Šumadijski okrug': 'sumadijski-okrug',
    'Toplički okrug': 'toplicki-okrug',
    'Zaječarski okrug': 'zajecarski-okrug',
    'Zapadnobački okrug': 'zapadnobacki-okrug',
    'Zlatiborski okrug': 'zlatiborski-okrug'
};