export const nameToSlugMap: Record<string, string> = {
    Naslovna: '', // display all posts
    Danas: 'danas',
    Politika: 'politika',
    Energetika: 'energetika',
    Privreda: 'privreda',
    Bezbednost: 'bezbednost',
    Ekonomija: 'ekonomija',
    Društvo: 'drustvo',
    Obrazovanje: 'obrazovanje',
    Tehnologija: 'tehnologija',
    Turizam: 'turizam',
    Zdravstvo: 'zdravstvo',
    Sport: 'sport',
    Kultura: 'kultura',
    Događaji: 'dogadjaji',
    Region: 'region',
    Planeta: 'planeta',
    'Latin | Ćirilica': 'latin-cirilica',
    Lokal: 'lokal',
    Beograd: 'beograd',
    Gradovi: 'gradovi',
    Okruzi: 'okruzi',
    Barajevo: 'barajevo',
    Čukarica: 'cukarica',
    Grocka: 'grocka',
    Lazarevac: 'lazarevac',
    Mladenovac: 'mladenovac',
    'Novi Beograd': 'novi-beograd',
    Palilula: 'palilula',
    Obrenovac: 'obrenovac',
    Rakovica: 'rakovica',
    'Savski venac': 'savski-venac',
    Sopot: 'sopot',
    'Stari grad': 'stari-grad',
    Surčin: 'surcin',
    Voždovac: 'vozdovac',
    Vračar: 'vracar',
    Zemun: 'zemun',
    Zvezdara: 'zvezdara',
};